### ISSUE TITLE
Overriding  of Creators of sub classes

### ISSUE THREAD

**Issue by KarstenBlume** [caelcs/builder4test#31]
Hello, 
is it possible to override the fields of a sub entity which was created by a sub creator?
BR
Karsten

**Comment by caelcs** [comment]
Hello

If I understand correctly you can find a way to achieve this by looking at this test

https://github.com/caelcs/builder4test/blob/0f87e05dde1e970554bef106d0a27876df75c5fa/src/test/java/integration/BuilderIntegrationTest.java#L143

The integration tests in that Test Class are real examples. It contains almost all the use cases.

**Comment by caelcs** [comment]
Also

https://github.com/caelcs/builder4test#reuse-and-composition-of-creators

Hope this answer your question.

**Comment by KarstenBlume** [comment]
Hi, 
i am sorry to refine my answer. I have a creator using the objects builder like this:
    public static Function<LookUp, VendorDTO> defaultVendorCreator = (lookUp) ->
            VendorDTO.builder()
                    .addresses(new HashSet<>(List.of(build().entity(defaultAddressCreator).get())))
                    .customersCodes(List.of(build().entity(defaultExternalCustomerCodesCreator).get()))
                    .auditoryData(build().entity(defaultAuditoryDataCreator).get())
                    .status(lookUp.get(status))
                    .name(lookUp.get(name))
                    .vendorId(build().entity(defaultVendorIdCreator).get())
                    .build();
Now i would like to overwrite some of the values/fields for another test case in (for example auditoryData fields) an object which is created by another creator.
build().entity( VendorDTOBuilder.defaultVendorCreator).applyValue(fieldFromAuditoryData, "newValue").get();

But overriding does not work. What is the culprit here?
BR
Karsten

**Comment by caelcs** [comment]
Thx... I will write a test case and see the issue or provide a way to work with the DSL. :)

**Comment by caelcs** [comment]
Ok... after looking into this. I can see why is not working for you.
I think that this is an equivalent scenario of what you are trying to achieve.

```
public static Field<String> name2 = new Field<>("defaultName");

public static Field<String> testValue = new Field<>();

public static Function<LookUp, String> valueTestCreator = lookUp -> lookUp.get(testValue, "test1");

public static Function<LookUp, Pojo> creatorWithPredefinedCreatorDefaults = lookUp -> new Pojo(lookUp.get(name2, valueTestCreator),
            lookUp.get(value2));
```

As you can see the main creator 'creatorWithPredefinedCreatorDefaults' is using 'valueTestCreator' to set the value of name.

Here is How the DSL would look like using it from a test:

```
        //When
        Pojo pojo1 = Builder.build()
                .entity(creatorWithPredefinedCreatorDefaults)
                .applyValue(testValue, "newvalue")
                .get();

        //Then
        assertThat(pojo1.getName()).isEqualTo("newvalue");
        assertThat(pojo1.getValue()).isEqualTo("defaultValue");
 ```

 The difference is that you are executing the creators within your main creator, you are not using lookup to glue all together.

 ```
public static Function<LookUp, VendorDTO> defaultVendorCreator = (lookUp) ->
VendorDTO.builder()
.addresses(new HashSet<>(List.of(build().entity(defaultAddressCreator).get())))
.customersCodes(List.of(build().entity(defaultExternalCustomerCodesCreator).get()))
.auditoryData(build().entity(defaultAuditoryDataCreator).get())
.status(lookUp.get(status))
.name(lookUp.get(name))
.vendorId(build().entity(defaultVendorIdCreator).get())
.build();

 ```
I would suggest to use it slightly different, like this:

 ```
public static Function<LookUp, VendorDTO> defaultVendorCreator = (lookUp) ->
VendorDTO.builder()
.addresses(new HashSet<>(List.of(lookup.get(addresses, defaultAddressCreator))))
.customersCodes(List.of(lookup.get(customerCodes, defaultExternalCustomerCodesCreator)))
.auditoryData(lookup.get(auditoryData, defaultAuditoryDataCreator))
.status(lookUp.get(status))
.name(lookUp.get(name))
.vendorId(lookup.get(vendorId, defaultVendorIdCreator)
.build();

 ```

 I think that by using it like that you will be able to override. 
 I will add this case as a integration test as well but I have ran it locally and it works.
